#sbatch -J c_ccpcvtz_k4_C_1s_nvir_act30 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py c_ccpcvtz_k4_C_1s_nvir_act30.json
sbatch -J c_ccpcvtz_k3_C_1s /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py c_ccpcvtz_k3_C_1s.json
#sbatch -J si_ccpcvtz_k4_Si_2p_nvir_act14 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py si_ccpcvtz_k4_Si_2p_nvir_act14.json
#sbatch -J si_ccpcvtz_k3_Si_2p_nvir_act52 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py si_ccpcvtz_k3_Si_2p_nvir_act52.json
#sbatch -J bn_ccpcvtz_k4_N_1s_nvir_act30 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k4_N_1s_nvir_act30.json
#sbatch -J bn_ccpcvtz_k3_N_1s_nvir_act30 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k3_N_1s_nvir_act30.json
#sbatch -J bn_ccpcvtz_k3_N_1s /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k3_N_1s.json
#sbatch -J bn_ccpcvtz_k2_N_1s /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k2_N_1s.json
#sbatch -J bn_ccpcvtz_k4_B_1s_nvir_act30 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k4_B_1s_nvir_act30.json
#sbatch -J bn_ccpcvtz_k3_B_1s_nvir_act30 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k3_B_1s_nvir_act30.json
#sbatch -J bn_ccpcvtz_k2_B_1s_nvir_act30 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k2_B_1s_nvir_act30.json
#sbatch -J bn_ccpcvtz_k3_B_1s /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k3_B_1s.json
#sbatch -J bn_ccpcvtz_k2_B_1s /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py bn_ccpcvtz_k2_B_1s.json
#sbatch -J aln_ccpcvtz_k4_N_1s_nvir_act6 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k4_N_1s_nvir_act6.json
#sbatch -J aln_ccpcvtz_k3_N_1s_nvir_act6 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k3_N_1s_nvir_act6.json
#sbatch -J aln_ccpcvtz_k2_N_1s_nvir_act6 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k2_N_1s_nvir_act6.json
#sbatch -J aln_ccpcvtz_k3_N_1s_nvir_act39 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k3_N_1s_nvir_act39.json
#sbatch -J aln_ccpcvtz_k2_N_1s_nvir_act39 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k2_N_1s_nvir_act39.json
#sbatch -J aln_ccpcvtz_k2_N_1s /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k2_N_1s.json
#sbatch -J aln_ccpcvtz_k4_Al_2p_nvir_act6 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k4_Al_2p_nvir_act6.json
#sbatch -J aln_ccpcvtz_k3_Al_2p_nvir_act6 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k3_Al_2p_nvir_act6.json
#sbatch -J aln_ccpcvtz_k2_Al_2p_nvir_act6 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k2_Al_2p_nvir_act6.json
#sbatch -J aln_ccpcvtz_k3_Al_2p_nvir_act39 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k3_Al_2p_nvir_act39.json
#sbatch -J aln_ccpcvtz_k2_Al_2p_nvir_act39 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k2_Al_2p_nvir_act39.json
#sbatch -J aln_ccpcvtz_k2_Al_2p /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py aln_ccpcvtz_k2_Al_2p.json
#sbatch -J alp_ccpcvtz_k4_Al_2p_nvir_act14 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py alp_ccpcvtz_k4_Al_2p_nvir_act14.json
#sbatch -J alp_ccpcvtz_k3_Al_2p_nvir_act14 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py alp_ccpcvtz_k3_Al_2p_nvir_act14.json
#sbatch -J alp_ccpcvtz_k2_Al_2p_nvir_act14 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py alp_ccpcvtz_k2_Al_2p_nvir_act14.json
#sbatch -J alp_ccpcvtz_k3_Al_2p_nvir_act52 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py alp_ccpcvtz_k3_Al_2p_nvir_act52.json
#sbatch -J alp_ccpcvtz_k2_Al_2p_nvir_act52 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py alp_ccpcvtz_k2_Al_2p_nvir_act52.json
#sbatch -J alp_ccpcvtz_k2_Al_2p /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py alp_ccpcvtz_k2_Al_2p.json
#sbatch -J mgo_ccpcvtz_k4_O_1s_nvir_act21 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k4_O_1s_nvir_act21.json
#sbatch -J mgo_ccpcvtz_k3_O_1s_nvir_act21 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k3_O_1s_nvir_act21.json
#sbatch -J mgo_ccpcvtz_k2_O_1s_nvir_act21 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k2_O_1s_nvir_act21.json
#sbatch -J mgo_ccpcvtz_k3_O_1s_nvir_act63 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k3_O_1s_nvir_act63.json
#sbatch -J mgo_ccpcvtz_k2_O_1s_nvir_act63 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k2_O_1s_nvir_act63.json
#sbatch -J mgo_ccpcvtz_k2_O_1s /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k2_O_1s.json
#sbatch -J mgo_ccpcvtz_k4_Mg_2p_nvir_act21 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k4_Mg_2p_nvir_act21.json
#sbatch -J mgo_ccpcvtz_k3_Mg_2p_nvir_act21 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k3_Mg_2p_nvir_act21.json
#sbatch -J mgo_ccpcvtz_k2_Mg_2p_nvir_act21 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k2_Mg_2p_nvir_act21.json
#sbatch -J mgo_ccpcvtz_k3_Mg_2p_nvir_act63 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k3_Mg_2p_nvir_act63.json
#sbatch -J mgo_ccpcvtz_k2_Mg_2p_nvir_act63 /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k2_Mg_2p_nvir_act63.json
#sbatch -J mgo_ccpcvtz_k2_Mg_2p /burg/berkelbach/users/eav2136/builds/work_tools/slurm/pyscf/pyscf-job.sh base.py mgo_ccpcvtz_k2_Mg_2p.json
